computacao-periodo1-volume1:
  -
    url: https://github.com/edusantana/matematica-elementar-livro/releases/download/v2.3.0/matematica-elementar-livro-v2.3.0.pdf
    stamp: stamps/1-me.pdf
  -
    url: https://github.com/edusantana/introducao-a-ead-livro/releases/download/v1.0.4/introducao-a-ead-livro-v1.0.4.pdf
    stamp: stamps/2-iead.pdf
computacao-periodo1-volume2:
  -
    url: https://github.com/edusantana/introducao-a-computacao-livro/releases/download/v1.0.5/introducao-a-computacao-livro-v1.0.5.pdf
    stamp: stamps/2-iead.pdf
  -
    url: https://github.com/edusantana/fundamentos-socio-historico-da-educacao-livro/releases/download/v1.0.4/fundamentos-socio-historico-da-educacao-livro-v1.0.4.pdf
    stamp: stamps/1-me.pdf
  -
    url: https://github.com/edusantana/introducao-a-programacao-livro/releases/download/v1.0.0/introducao-a-programacao-livro-v1.0.0.pdf
    stamp: stamps/2-iead.pdf
